version: "3.9"
services:
  server:
    container_name: server
    build: ./dichtruyen.Server
    restart: always
    privileged: true
    ports:
      - 80:8080
      - 5001:8081
    networks:
          - web_net
    volumes:
      - ./dichtruyen.client/dist/dichtruyen.client/browser:/app/wwwroot:rw

  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
    - pgdata:/var/lib/postgresql/data
    ports:
    - 5432:5432

networks:
    web_net:
      external: false
      driver:  bridge

volumes:
  rabbitmq_data:
    driver: local
  pgdata: